# Generated by Django 4.2.9 on 2024-02-11 17:53

import MainApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='server_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=1024, unique=True)),
                ('personal_key', models.CharField(default='personal_key', max_length=64)),
                ('main_server_access_token', models.CharField(max_length=1024, unique=True)),
                ('main_server_refresh_token', models.CharField(max_length=1024, unique=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Folder', max_length=256)),
                ('parent', models.CharField(default='root', max_length=256)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='MainApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=MainApp.models.user_directory_path)),
                ('name', models.CharField(default='file', max_length=256)),
                ('parent', models.CharField(default='root', max_length=256)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='MainApp.folder')),
            ],
        ),
    ]
