# Generated by Django 4.2.7 on 2023-12-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='server_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_server_access_token', models.CharField(max_length=1024, unique=True)),
                ('main_server_refresh_token', models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='main_user_model',
            name='access_token',
            field=models.CharField(default='access_token', max_length=1024),
        ),
        migrations.AddField(
            model_name='main_user_model',
            name='refresh_token',
            field=models.CharField(default='refresh_token', max_length=1024),
        ),
        migrations.AddField(
            model_name='main_user_model',
            name='secret_key',
            field=models.CharField(default='secret_key', max_length=64),
        ),
    ]
