# Generated by Django 4.2.19 on 2025-03-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='taken_space',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='server_data',
            name='personal_key',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='available_space',
            field=models.BigIntegerField(default=16106127360),
        ),
    ]
