# Generated by Django 4.2.7 on 2023-12-20 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_server_data_main_user_model_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_user_model',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server_data',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server_data',
            name='local_server_access_token',
            field=models.CharField(default='token', max_length=1024, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server_data',
            name='local_server_refresh_token',
            field=models.CharField(default='token', max_length=1024, unique=True),
            preserve_default=False,
        ),
    ]
