# Generated by Django 4.2.5 on 2023-10-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_user_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='node_ip',
        ),
    ]
