# Generated by Django 4.2.5 on 2023-10-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_remove_user_node_ip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CloudUser',
        ),
    ]
