# Generated by Django 4.2.7 on 2023-12-20 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_main_user_model_date_added_server_data_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_user_model',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='server_data',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='server_data',
            name='local_server_access_token',
        ),
        migrations.RemoveField(
            model_name='server_data',
            name='local_server_refresh_token',
        ),
    ]
