# Generated by Django 4.2.5 on 2023-10-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_clouduser_options_alter_clouduser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clouduser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
