# Generated by Django 4.2.7 on 2023-12-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_main_user_model_date_added_server_data_date_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_user_model',
            old_name='access_token',
            new_name='user_access_token',
        ),
        migrations.RenameField(
            model_name='main_user_model',
            old_name='refresh_token',
            new_name='user_refresh_token',
        ),
    ]
