# Generated by Django 4.2.8 on 2024-01-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_rename_access_token_main_user_model_user_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_user_model',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='main_user_model',
            name='password',
        ),
        migrations.AlterField(
            model_name='server_data',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
