# Generated by Django 4.2.5 on 2023-10-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_rename_node_domain_clouduser_node_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clouduser',
            old_name='node',
            new_name='node_domain',
        ),
    ]
