# Generated by Django 4.2.8 on 2024-01-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_remove_main_user_model_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_user_model',
            name='user_access_token',
        ),
        migrations.RemoveField(
            model_name='main_user_model',
            name='user_refresh_token',
        ),
        migrations.RemoveField(
            model_name='server_data',
            name='local_server_access_token',
        ),
        migrations.RemoveField(
            model_name='server_data',
            name='local_server_refresh_token',
        ),
    ]
