# Generated by Django 4.2.8 on 2024-01-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_remove_main_user_model_user_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_data',
            name='personal_key',
            field=models.CharField(default='personal_key', max_length=64),
        ),
    ]
