# Generated by Django 4.2.5 on 2023-10-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_rename_node_clouduser_node_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_domain', models.CharField(max_length=20, unique=True)),
                ('ip_address', models.CharField(max_length=12, unique=True)),
                ('user_quantity', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
