# Generated by Django 4.2.9 on 2024-01-31 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_file_folder_user_remove_user_data_model_username_and_more'),
    ]

    operations = [
    ]
