# Generated by Django 4.2.9 on 2024-01-31 15:13

import MainApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_auto_20240131_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=MainApp.models.user_directory_path),
        ),
    ]
