# Generated by Django 4.2.9 on 2024-02-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(default='Folder', max_length=256),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.CharField(default='Root', max_length=256),
        ),
    ]
