# Generated by Django 4.2.9 on 2024-02-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_alter_folder_name_alter_folder_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='parent',
            field=models.CharField(default='Root', max_length=256),
        ),
    ]
