# Generated by Django 4.2.9 on 2024-02-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_file_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='folder',
        ),
    ]
