"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/ """
from django.urls import reverse_lazy
from pathlib import Path
import os

EX_IP = os.environ.get('EX_IP')
IN_IP = os.environ.get('IN_IP')
HOSTNAME = os.environ.get('HOSTNAME')

ALLOWED_HOSTS = [
    IN_IP, 
    EX_IP, 
    'localhost', 
    '127.0.0.1', 
    "whoole.space", 
    HOSTNAME + ".whoole.space", 
    "home.whoole.space", 
    "176.197.34.213"
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost",
    "http://127.0.0.1",

]

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    "https://192.168.0.98",
    "http://192.168.0.98",
    
    "https://192.168.0.81",
    "http://192.168.0.81",

    "http://127.0.0.1",
    "https://127.0.0.1",

    "https://176.197.34.213",
    "http://176.197.34.213",

    "https://whoole.space",
    "http://whoole.space",
]

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SERVER_CERTIFICATE = '/server.pem'
SERVER_KEY = '/serverkey.pem'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f790b_syh@as9^%j(e290_k8mgsq=7mgznh^g0eu(231#w+j!l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'MainApp.apps.MainConfig',
    'crispy_forms',
    'crispy_bootstrap5',
    'sslserver',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.common.CommonMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',     # 1
    'django.contrib.messages.middleware.MessageMiddleware',     # 2
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # 3
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'MainApp.middleware.TokenAuthMiddleware',
]

SECURE_REFERRER_POLICY = 'no-referrer'

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DBNAME'),
        'PASSWORD': os.environ.get('DBPASSWORD'),
        'USER': 'django_user',
        'HOST': '/var/run/postgresql',
        'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
#       os.path.join(BASE_DIR, "static"),
   ]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'auth.User'

CSRF_COOKIE_NAME = 'csrftoken'

#LOGGING = {
#   'version': 1,
#   'disable_existing_loggers': False,
#   'handlers': {
#       'console': {
#           'class': 'logging.StreamHandler',
#       },
#       'file': {
#           'level': 'DEBUG',
#           'class': 'logging.FileHandler',
#           'filename': '/var/log/django/debug.log',
#       },
#   },
#   'root': {
#       'handlers': ['console', 'file'],
#       'level': 'INFO',
#   },
#   'loggers': {
#       'django': {
#           'handlers': ['console', 'file'],
#           'level': 'DEBUG',
#           'propagate': True,
#       },
#   },
#}

CORS_ALLOWED_ORIGINS = [
    'https://192.168.0.98',
    'http://192.168.0.98',
]

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)
